version: '3'
services:
  app:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    # volumes:
    #   - ./data:/app/

# version: '3'
# services:
#   app:
#     build:
#       context: .
#       dockerfile: Dockerfile
#     ports:
#       - 5003:5003
#     volumes:
#       - ./job_data.csv:/app/job_data.csv
